USE test;

CREATE TABLE CUSTOMER(
C_ID INT,
C_NAME VARCHAR(25),
PRIMARY KEY(C_ID)
);

CREATE TABLE ORDERS(
ORDER_ID INT,
ORDER_NO INT,
FOREIGN KEY(ORDER_ID) REFERENCES CUSTOMER(C_ID)
);

INSERT INTO CUSTOMER VALUES(001,'SACHIN'),
(002,'VAIBHAVI'),
(003,'JINAL'),
(004,'NAVYA'),
(005,'SONAL');

INSERT INTO ORDERS VALUES(001,01),
(002,02),
(003,03),
(004,04),
(005,05);

SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

SELECT * FROM CUSTOMER WHERE C_NAME LIKE ('_A%');

CREATE TABLE ACCOUNT_INDIA(
ACC_ID INT PRIMARY KEY,
ACC_NAME VARCHAR(20) UNIQUE,
BALANCE INT NOT NULL DEFAULT 0
);

INSERT INTO ACCOUNT_INDIA VALUES (001,'SACHIN',1500),
(002,'VAIBHAVI',150),
(003,'JINAL',1600),
(004,'JAYASHREE',1700),
(005,'VINAA',1800);
-- REPLACE DATA
REPLACE INTO ACCOUNT_INDIA SET ACC_ID=001,ACC_NAME='ARCHNAA';

-- UPDATE VALUES 
UPDATE ACCOUNT_INDIA SET BALANCE=15000 , ACC_NAME='KARAN' WHERE ACC_ID = 005;
-- E.G
SELECT  * FROM ACCOUNT;

SELECT BALANCE FROM ACCOUNT_INDIA WHERE BALANCE=15000;

SELECT BALANCE ,COUNT(BALANCE) FROM ACCOUNT_INDIA GROUP BY BALANCE;

-- UPDATE MULTIPLE ROWS

SET SQL_SAFE_UPDATES = 0;

UPDATE ACCOUNT_INDIA SET BALANCE = 1000; 
-- DELET CUTSOMER

DELETE FROM ACCOUNT_INDIA WHERE ACC_ID = 005;
DELETE FROM ACCOUNT_INDIA;

-- RENAME

ALTER TABLE ACCOUNT_INDIA RENAME TO ACCOUNT;
