-- q.1 FETCH FIRST NAME FROM WORKER TABLE ALISE AS EMP_NAME
SELECT FIRST_NAME AS EMP_NAME FROM EMP;

-- Q.2 FETCH FIRST NAME AND DISPALY DATA IN LOWER CASE

SELECT UPPER(FIRST_NAME) FROM EMP;
 
--  WRITE Q TO FETCH ONLY UNIQ DEP FROM EMP TABLE 
SELECT DISTINCT DEPARTMENT FROM EMP;

-- USING GROUP BY WE CAN ALSO SOLVE THIS Q.3
SELECT DEPARTMENT FROM EMP GROUP BY DEPARTMENT;

-- Q.4 WRQ TO DISPLAY ONLY FIRST THREEE CHR OF FIRST NAME FROM EMP
SELECT SUBSTR(FIRST_NAME, 1,3)  FROM EMP;

-- Q.5 FETCH POSTION OF R FROM KARAN STR FROM FIRST NAME

SELECT INSTR(FIRST_NAME, 'R') FROM EMP WHERE FIRST_NAME = 'KARAN';

-- Q.6 REMOVE WHITE SPACE FROM RIGHT SIDE OF FIRST NAME

SELECT RTRIM(FIRST_NAME)  FROM EMP; 

-- U CAN USE L TRIM FOR LEFT SIDE WHITE SAPCE RAMOVING

-- Q.7 WRQ TO FETCH UNIQ VALUE AND THEIR LENGHT FROM DEP IN EMP TABLE

SELECT  distinct DEPARTMENT,  length(DEPARTMENT)  FROM EMP; 

-- Q.8 WRQ TO REPLACE SMALL A TO B CAPITAL IN FIRST_NAME
SELECT REPLACE(FIRST_NAME, 'A','B')FROM EMP;

-- Q.9 WRQ TO PRINT F NAME WITH LAST NAME IN SAME COLUMN 
SELECT CONCAT(FIRST_NAME, ' ',LAST_NAME) AS EMP_NAME FROM EMP;

-- Q.10 WRQ PRINT ALL EMP DETAILS FROM EMP TABLE ORDER BY FIRST NAME
SELECT * FROM EMP ORDER BY FIRST_NAME ASC; 

-- Q.11  WRQ PRINT ALL EMP DETAILS FROM EMP TABLE ORDER BY FIRST NAME ASC AND DEPARTMENT DESC
SELECT * FROM EMP ORDER BY FIRST_NAME , DEPARTMENT DESC; 

-- Q.12 WRQ PRINT EMP DETAILS OF F NAME WHERE NAME JINAL AND VAIBHVAI
SELECT * FROM EMP WHERE FIRST_NAME IN ('JINAL','VAIBHAVI'); 

-- Q.13 WRQ PRINT EMP DETAILS OF F NAME WHERE NAME EXLUDING JINAL AND VAIBHVAI
SELECT * FROM EMP WHERE FIRST_NAME NOT IN ('JINAL','VAIBHAVI'); 

-- Q.14 WRQ TO PRINT DEP WHRE DEP (ADMIN*)
SELECT * FROM EMP WHERE DEPARTMENT LIKE 'ADMIN%';
-- Q.15 WRQ PRINT EMP FIRST NAME CONTAINS 'A'
SELECT * FROM EMP WHERE FIRST_NAME LIKE '%A%';
-- Q.16 WRQ PRINT DETAILS OF EMP WHO'S FIRST_NAAME END WITH H AND CONTAINS 5 ALPHABETS
SELECT * FROM EMP WHERE FIRST_NAME LIKE '____H%';
-- Q.17 WRQ EMP SALARY BW 100 - 1000
SELECT * FROM EMP WHERE SALARY BETWEEN 100 AND 1000;
-- Q.18 WRQ TO PRINT EMP WHO JOIN IN 2014/2
SELECT * FROM EMP WHERE YEAR(JOINING_DATE) = 2014 AND MONTH(JOINING_DATE) = 02;
-- Q.19 WRQ TO GET COUNT OF EMP WPORKING IN 'TECH' DEP
SELECT DEPARTMENT, COUNT(*) FROM EMP WHERE DEPARTMENT = 'TECH';
-- Q.20 WRQ TO GET FULL NAME OF EMP WWHO'S SALARY IS 500>=1000 
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME)AS EMP_FULLNAME FROM EMP WHERE SALARY BETWEEN 100 AND 1000;
-- Q.21 WRQ TO GET EACH EMP FOR EACH NO . OF DEP
SELECT DEPARTMENT, COUNT(EMP_ID) FROM EMP GROUP BY DEPARTMENT ORDER BY COUNT(EMP_ID) DESC;
-- Q.22 WRQ TO GET EMP WHO IS MANAGER 
SELECT * FROM EMP AS E INNER JOIN TITLE AS T ON E.EMP_ID = T.EMP_ID WHERE T.EMP_TITLE = 'MANAGER';
-- q.23 wrq number of same titles in org of diff diff types
SELECT EMP_TITLE , COUNT(*) FROM TITLE GROUP BY EMP_TITLE HAVING COUNT(*) > 1;
-- Q.24 SHOW ONLY ODD NUMBER OF EMP_ID
SELECT * FROM EMP WHERE MOD(EMP_ID,2) != 0;
-- Q.25 WRQ TO CLONE NEW TABLE FROM ANOTHER TABLE
CREATE TABLE EMP_CLONE LIKE EMP;
INSERT INTO EMP_CLONE SELECT * FROM EMP;
SELECT * FROM EMP_CLONE;

-- Q.25 WRQ TO INTERSECT  DATA FROM TWO TABLE
SELECT EMP.*  FROM EMP INNER JOIN EMP_CLONE USING(EMP_ID); -- WHERE EMP_CLONE.EMP_ID IS NULL;

-- Q.26 SHOW THE DATA OF ONE TABLE THAT ANOTHER TABLE DOESN'T HAVE
SELECT *  FROM EMP LEFT JOIN EMP_CLONE USING(EMP_ID) WHERE EMP_CLONE.EMP_ID IS NULL;

-- Q.27 WRQ TO SHOW CURRNT DADTE AND TIME
SELECT CURDATE();
SELECT NOW();

-- Q. 28  GET TOP 5 SALARY OF EMP IN desc
SELECT * FROM EMP ORDER BY SALARY LIMIT 5;

-- Q. 29 PRINT EMP WHO'S SALARY'S ARE SAME
SELECT E1.* FROM EMP E1,EMP E2 WHERE E1.SALARY = E2.SALARY AND E1.EMP_ID != E2.EMP_ID; 
-- Q.30 PRINT HIGHEST SALARY FROM EMP
SELECT *, MAX(SALARY) FROM EMP;
-- Q.31  PRINT SECOND HIGHEST SALARY FROM EMP
SELECT MAX(SALARY) FROM EMP 
WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM EMP);

-- Q.32 WRQ TO PRINT DATA TWICE IN ONE TABLE
SELECT * FROM EMP 
UNION ALL
SELECT * FROM EMP;

-- Q.33 WRQ TO GET LIST EMP_ID WHO DEOSNT GET BONUS
SELECT *  FROM EMP WHERE EMP_ID NOT IN (SELECT EMP_REF_ID FROM BONUS);

-- Q.34 WRQ TO PRINT DEP THAT HVAING LESS THEN 3 PEPOLE
(SELECT DEPARTMENT, COUNT(DEPARTMENT) AS DEPCOUNT FROM EMP GROUP BY DEPARTMENT HAVING DEPCOUNT < 3);

-- Q. 33 WRQ TO SHOW ALL DEP ALONG WITH NO OF PEOPLE WORKING IN IT.
 SELECT DEPARTMENT, COUNT(DEPARTMENT) AS DEPCOUNT FROM EMP GROUP BY DEPARTMENT;
-- Q. 34 WRQ SHOW LAST RECORD IN TABLE
SELECT * FROM EMP WHERE EMP_ID =(SELECT MAX(EMP_ID) FROM EMP);
-- Q.35 WRQ SHOW FIRST RECORND IN TABLE
SELECT * FROM EMP WHERE EMP_ID =(SELECT MIN(EMP_ID) FROM EMP);
-- Q. 36 WRQ TO PRINT LAST 5 RECORD FROM EMP TABLE
(SELECT * FROM EMP ORDER BY EMP_ID DESC LIMIT 5) ORDER BY EMP_ID;
-- Q. 37 WRQ TO PRINT EMP NAME HAVING HIGEST SALARY IN EACH DEPARTMENT
-- I TRIED FIRST THIS :(
SELECT *FROM EMP WHERE SALARY = (SELECT MAX(SALARY) FROM EMP);
SELECT DEPARTMENT FROM EMP  WHERE SALARY = (SELECT MAX(SALARY) FROM EMP);

-- FINAL ANS :)
-- IMP
SELECT E.DEPARTMENT, E.FIRST_NAME, E.SALARY FROM 
(SELECT MAX(SALARY ) AS MAXSAL, DEPARTMENT   FROM EMP  GROUP BY DEPARTMENT) TEMP 
INNER JOIN EMP E ON TEMP.DEPARTMENT = E.DEPARTMENT AND TEMP.MAXSAL = E.SALARY;
--

-- Q. 37 WRQ TO FETH MAX THREE SALARY
SELECT distinct SALARY FROM EMP ORDER BY SALARY DESC LIMIT 3;
-- Q. 38 WRQ TO PRINT TOTAL SALARY FROM EACH DEP 
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SAL  FROM EMP GROUP BY DEPARTMENT;
-- Q.39 WRQ TO FETCH EMP NAME  EMP WHO HAS HIGHEST SALARY
SELECT FIRST_NAME ,SALARY FROM EMP WHERE SALARY = (SELECT MAX(SALARY) FROM EMP);  
-- Q.40 WRQ TO REMOVE ALL THE REVERSED NUMBER PAIR FOR GIVEVEN TABLE

CREATE TABLE PAIRS (
A INT,
B INT
);

INSERT INTO PAIRS VALUES(1,2),(2,1),(2,3),(3,2),(4,3),(3,4),(5,6),(6,5);

-- METHOD JOIN 
SELECT LEFT_T.* FROM PAIRS LEFT_T LEFT JOIN PAIRS RIGHT_T ON LEFT_T.A = RIGHT_T.B AND LEFT_T.B = RIGHT_T.A 
WHERE RIGHT_T.A IS NULL OR LEFT_T.A < RIGHT_T.A; 


